<?php
$Dir = "../..";
require $Dir . '/acm/SysFileAutoLoader.php';
require $Dir . '/app/onboarding/headers/HeaderRequests.php';

//pagevariables
$PageName = "Welcome to Self Onboarding Process & Documentation";
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title><?php echo $PageName; ?> | <?php echo APP_NAME; ?></title>
  <meta content="width=device-width, initial-scale=0.9, maximum-scale=1, user-scalable=no" name="viewport" />
  <meta name="keywords" content="<?php echo APP_NAME; ?>">
  <meta name="description" content="<?php echo SECURE(SHORT_DESCRIPTION, "d"); ?>">
  <?php include $Dir . "/assets/HeaderFiles.php"; ?>
</head>

<body>
  <section class="container mt-3 pb-5">
    <div class="row">
      <div class="col-md-12 text-left">
        <img src="<?php echo APP_LOGO; ?>" class="logo-onboarding mt-2">
        <h2 class="pt-2 bold mb-4"><?php echo APP_NAME; ?></h2>
        <h6 class="mb-2">Welcome to the Self Onboarding Process & Documentation for <?php echo APP_NAME; ?></h6>
        <p class="mb-3">Get started by filling out the required information. Please ensure that you complete all the mandatory fields. At the end of the process, all necessary documents must be submitted. If any details or documents are missing, you will not be able to complete the onboarding with <?php echo APP_NAME; ?>.</p>
        <ul>
          <li>Fill out your personal information including full name, address, and contact details.</li>
          <li>Provide your employment history and educational background.</li>
          <li>Upload a copy of your government-issued ID and proof of address.</li>
          <li>Submit any relevant certifications or licenses.</li>
          <li>Review and confirm all provided information before final submission.</li>
          <li>Onboarding url is only generated by <b>HR, Admin</b> & <b>Administrator</b> level only. this url is only valid for 24hr after generated time!.</li>
          <li>Candidate have to submit form within 48 hours otherwise they have to request for new onboarding link via HR.</li>
          <li>Document must be ready like id proofs, address proof, work experience certificates, photo, cancel cheque, and other supportive documents. Only jpg, jpeg, png, pdf, files are supported.</li>
          <li>selection of candidate may depend on the final analysis of submitted details!</li>
        </ul>
        <hr>

        <a href="process" class='btn btn-primary btn-md b-r-3 pull-right'> Start Onboarding <i class='fa fa-angle-right'></i></a>
        <?php if ($OnBoardingRequestedBy != null) { ?>
          <span class='pull-right btn btn-md'><i class='fa fa-lock text-success'></i> Login as <b><?php echo FETCH($UserSQL, "UserFullName"); ?></b></span>
        <?php } ?>
      </div>
    </div>
  </section>


  <?php
  include $Dir . "/app/onboarding/headers/FooterRights.php";
  include $Dir . "/assets/FooterFiles.php";
  ?>

</body>

</html>